name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          commit-message-template: "build(gradle): update gradle wrapper from %sourceVersion% to %targetVersion%"
          pr-title-template: "build(gradle): update gradle wrapper from %sourceVersion% to %targetVersion%"
          labels: dependencies
